function VisualizeGLSZM(zdata1)
%CREATEFIGURE(zdata1)
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 28-Mar-2020 00:14:36

% Create figure
figure1 = figure('InvertHardcopy','off');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.179036913851865 0.150477488495739 0.644289663268446 0.776568047272548]);
hold(axes1,'on');

% Create surf
surf(zdata1,'Parent',axes1,'MeshStyle','row','EdgeColor','none');

% Create zlabel
zlabel({'Number of occurrences of a ','particular size-zone'},...
    'FontSize',15.4,...
    'FontName','Times New Roman');

% Create ylabel
ylabel({'Grey-level intensities'},'FontSize',15.4,...
    'FontName','Times New Roman',...
    'Rotation',30);

% Create xlabel
xlabel({'Size-zones (or connectivity)'},'FontSize',15.4,...
    'FontName','Times New Roman',...
    'Rotation',-13);

% Create title
title({'GLSZM Representation'},'FontSize',15.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 110]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1 255]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 2000000]);
view(axes1,[32.6030204120156 27.9295258786299]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'CLim',[1 10000000],'ColorScale','log','FontName',...
    'Times New Roman','FontSize',14,'XMinorGrid','on','XTick',[0 25 50 75 110],...
    'XTickLabel',{'0','25','50','75','187'},'YMinorGrid','on','YTick',...
    [1 50 100 150 200 255],'YTickLabel',{'1','50','100','150','200','255'},...
    'ZMinorGrid','on');
% Create colorbar
colorbar(axes1,'Position',...
    [0.902809523809522 0.125873015873016 0.0380952380952374 0.815000000000001],...
    'FontSize',12.6);

